### PR TITLE
jsdom memory leak workaround

### PR DESCRIPTION
**Pull request by pirxpilot**
Call windown.close() after we are done with it to release memory.

See discussion here: http://stackoverflow.com/questions/5718391/memory-leak-in-node-js-scraper

### CODE REVIEW

**Comment by lmatteis** [comment]
@pirxpillot, I've tried your version and I get this error:

```
error: Dispatching event 'load' failed. - More:
[object Object]
undefined
error: Dispatching event 'load' failed. - More:
[object Object]
undefined

/Users/lucamatteis/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/events.js:175
    var listeners = target._listeners
                          ^
Called getGlobal() after dispose().
```

Once I remove `window.close()` it works, but still with memory leaking all over the place. Is there any solution for this or am I stuck with creating a child process for each one of my scrapes?

**Comment by pirxpilot** [comment]
It worked for me for a while, but I am now seeing the same problem you do. Not sure what, if anything, changed yet. Will post if I find out anything, but for now it looks like we are stuck with child processes.

**Comment by cjroebuck** [comment]
I'm also getting this problem after using `window.close()`

**Comment by jmonster** [comment]
i just saw this error today :(

**Comment by im924106179** [comment]
me too

**Comment by im924106179** [comment]
i think this article will be help:
http://lukeberndt.com/2011/jsdom-memory-leaks/
:)

**Comment by baio** [comment]
the same

**Pull request closed without merging**
